### ISSUE TITLE
"Grace trajectories" and a vertical/diagonal 0 trajectory

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#264]
Be able to have grace notes that begin or end a move up or down the scale within a phrase that falls between "pitches." Like the vibrato, but with trajectories 1, 2, 3. 

Also, consider making trajectory 0 apply for vertical and diagonal movements as well. We can do so if linked to trajectory 6, but sometimes one just needs a single line.

**Comment by jon-myers** [comment]
plan:
1. add a new attribute to `class Pitch` called `logOffset`, which defaults to 0. `pitch.frequency` will be changed to a getter function that takes `logOffset` into account, so that when Trajectory tries to assign `freqs` and `logFreqs` from its `pitches` array, it takes the offset value. 
2. add a context menu to right-clicks that occur on a `dragDot`. This will only be available when an individual trajectory is selected (i.e. not in a group or when multiple trajs are selected). The context menu will have an option for "vertical offset". Selecting this option will a) get rid of the context menu, b) change the color of the drag dot, c) allow you to drag the dot vertically (but not horizontally), with limits of the above and below sargam lines. 
3. As you drag, a shadow trajectory will show what the new one will look like. Upon finishing the drag, a new trajectory will be inserted.

**Comment by jon-myers** [comment]
I think this has all been implemented, so closing with pull request. Reopen if I missed something.
