### ISSUE TITLE
Section/Phrase

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#369]
When I add a new phrase and click the button to make it a section it often reverts back to a phrase.

Sometimes it "sticks" as a section; other times it does not.

Relatedly, go to the first Abdul Karim Khan Shuddh Kalyan in the sections 1:38 to 1:44. It jumps from section 9 to section 11 as if there is a ghost section 10.

**Comment by jon-myers** [comment]
I fixed the main bug: Now toggling between section / phrase should be working properly. 

As for the Abdul Karim Khan Shuddh Kalyan, I manually went in and deleted some strange data. The sectionStarts attribute on the transcription had a few of the sections beginning on phrase `null`. Instead of `null`, it should be an integer. I'm not sure how those `null`s were getting assigned, but I've just deleted them for now. Will have to watch out for when/if this problem happens again, and try to figure out how they are getting inserted.

**Comment by jon-myers** [comment]
I'm just noticing that there is another related issue: the "sectionCategorization" array is sometimes larger than the # of sections. Will have to 1. figure out why this is happening and stop it, and 2. figure out how to deal with the data now that this has been occuring.

**Comment by jon-myers** [comment]
I'm not sure why this was occurring, and I can't seem to recreate it. I am presently writing an aggregation to fix it in cases where it has happened (by just deleting the extra sectionCategorizations), but will leave this issue open so that I can circle back and see if it continues to happen ...
