### ISSUE TITLE
Pushed to invisible but audible octaves

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#379]
Vilayat Khan Raga Yaman: Minute 18:45

I was transcribing some basic movements in serial mode. I was in the upper register as it was more visible. I finished, marked the circumference around the set, hit the button to move it an octave below. Some went an octave below, some two octaves below. The notes two octaves below I moved up individually. That somehow made them all (but one) go an octave and two below, in the wonderful space that's unseen but heard. It sounds groovy (:

Another one went below at 18:57 and there's really nothing I did (that I can think of) that made that happen.

**Comment by Dard-Neuman** [comment]
It also happened from 18:04-18:16. I didn't use the octave switch on this series. But on both I used the Serial mode.

**Comment by jon-myers** [comment]
The fact that it happened in "serial mode" is a good clue. We had this problem previously, and I fixed it, but probably did not make the appropriate changes in the "serial mode" entry functions. My guess is that when the code enters a fixed trajectory via serial mode, It uses two instances of the same Pitch object, instead of two unique objects for each of the two pitches. This means that, for those badly formed fixed trajectories, when we call the function to shift one octave down for all of the pitches in the trajectory, it ends up going down two octaves, since it is happening twice. (Sorry, maybe that was too much info, but I think I will be able to track it down now)

**Comment by jon-myers** [comment]
I think this has been addressed, especially with the overhaul.
